services:
  - type: static
    name: trivia-client
    env: static
    buildCommand: ./render-build.sh
    publishDir: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://trivia-server.onrender.com

  - type: web
    name: trivia-server
    env: node
    buildCommand: ./render-build.sh
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
